DROP TABLE IF EXISTS SWIGGY_ANALYSIS;

--CREATE A TABLE TO IMPORT SWIGGY_DATA.CSV FILE

CREATE TABLE SWIGGY_ANALYSIS(
	COLUMN_ID SERIAL PRIMARY KEY,
	STATES VARCHAR(50),
	CITY VARCHAR(50),
	ORDER_DATE DATE,
	RESTAURANT_NAME VARCHAR(100),
	LOCATIONS VARCHAR(100),
	CATEGORY VARCHAR(100),
	NAME_OF_THE_DISH VARCHAR(250),
	PRICE NUMERIC(10,2),
	RATING NUMERIC(10,2),
	RATING_COUNT INT
	
	
);
SELECT * FROM SWIGGY_ANALYSIS;


-------------------------------------------------------
--CHECK THE NULL VALUES IN THE GIVEN DATASET IF PRESENT
-------------------------------------------------------
SELECT
	SUM(
		CASE
			WHEN STATES IS NULL THEN 1
			ELSE 0
		END
	) AS STATE_NULL_VALUE,
	SUM(
		CASE
			WHEN CITY IS NULL THEN 1
			ELSE 0
		END
	) AS CITY_NULL_VALUE,
	SUM(
		CASE
			WHEN ORDER_DATE IS NULL THEN 1
			ELSE 0
		END
	) AS ORDER_DATE_NULL_VALUE,
	SUM(
		CASE
			WHEN RESTAURANT_NAME IS NULL THEN 1
			ELSE 0
		END
	) AS RESTAURANT_NAME_NULL_VALUE,
	SUM(
		CASE
			WHEN LOCATIONS IS NULL THEN 1
			ELSE 0
		END
	) AS LOCATION_NULL_VALUE,
	SUM(
		CASE
			WHEN CATEGORY IS NULL THEN 1
			ELSE 0
		END
	) AS CATEGORY_NULL_VALUE,
	SUM(
		CASE
			WHEN NAME_OF_THE_DISH IS NULL THEN 1
			ELSE 0
		END
	) AS NAME_OF_THE_DISH_NULL_VALUE,
	SUM(
		CASE
			WHEN PRICE IS NULL THEN 1
			ELSE 0
		END
	) AS PRICE_NULL_VALUE,
	SUM(
		CASE
			WHEN RATING IS NULL THEN 1
			ELSE 0
		END
	) AS RATING_NULL_VALUE,
	SUM(
		CASE
			WHEN RATING_COUNT IS NULL THEN 1
			ELSE 0
		END
	) AS RATING_COUNT_NULL_VALUE
FROM
	SWIGGY_ANALYSIS;

----------------------------------	
--CHECK FOR BLANK OR EMPTY STRINGS
----------------------------------
SELECT
	*
FROM
	SWIGGY_ANALYSIS
WHERE
	STATES = ''
	OR CITY = ''
	OR RESTAURANT_NAME = ''
	OR LOCATIONS = ''
	OR CATEGORY = ''
	OR NAME_OF_THE_DISH = '';

----------------------	
--DUPLICATE DETECTION
----------------------
SELECT
	STATES,
	CITY,
	ORDER_DATE,
	RESTAURANT_NAME,
	LOCATIONS,
	CATEGORY,
	NAME_OF_THE_DISH,
	PRICE,
	RATING,
	RATING_COUNT,
	COUNT(*) AS CNT
FROM
	SWIGGY_ANALYSIS
GROUP BY
	STATES,
	CITY,
	ORDER_DATE,
	RESTAURANT_NAME,
	LOCATIONS,
	CATEGORY,
	NAME_OF_THE_DISH,
	PRICE,
	RATING,
	RATING_COUNT
HAVING
	COUNT(*) > 1;
	
------------------------------
--DROPPING THE DUPLICATE ITEMS
------------------------------
DELETE FROM SWIGGY_ANALYSIS AS T1 USING (
	SELECT
		COLUMN_ID,
		ROW_NUMBER() OVER (
			PARTITION BY
				STATES,
				CITY,
				ORDER_DATE,
				RESTAURANT_NAME,
				LOCATIONS,
				CATEGORY,
				NAME_OF_THE_DISH,
				PRICE,
				RATING,
				RATING_COUNT
			ORDER BY
				COLUMN_ID
		) AS RN
	FROM
		SWIGGY_ANALYSIS
) AS T2
WHERE
	T1.COLUMN_ID = T2.COLUMN_ID
	AND T2.RN > 1;
	
----------------------------------------------------------------	
--------------------DIMENSIONAL MODELING------------------------
----------------------------------------------------------------

--DIM FOR DATE

CREATE TABLE DIM_DATE (
	DATE_ID INT GENERATED ALWAYS AS IDENTITY (
		START
		WITH
			1 INCREMENT BY 1
	) PRIMARY KEY,
	FULL_DATE DATE,
	YEARS INT,
	MONTHS INT,
	MONTH_NAME VARCHAR(20),
	QUARTER INT,
	DAYS INT,
	WEEK INT
);

SELECT * FROM dim_date

--create dim for location

CREATE TABLE DIM_LOCATION (
	LOCATION_ID INT GENERATED ALWAYS AS IDENTITY (
		START
		WITH
			1 INCREMENT BY 1
	) PRIMARY KEY,
	STATES VARCHAR(50),
	CITY VARCHAR(50),
	LOCATIONS VARCHAR(50)
);

SELECT * FROM dim_location

--create dim for restaurant name

DROP TABLE IF EXISTS DIM_RESTAURANT;
CREATE TABLE DIM_RESTAURANT (
	RESTAURANT_ID INT GENERATED ALWAYS AS IDENTITY (
		START
		WITH
			1 INCREMENT BY 1
	) PRIMARY KEY,
	RESTAURANT_NAME VARCHAR(100)
);

--cretae dim for category

CREATE TABLE DIM_CATEGORY (
	CATEGORY_ID INT GENERATED ALWAYS AS IDENTITY (
		START
		WITH
			1 INCREMENT BY 1
	) PRIMARY KEY,
	CATEGORY VARCHAR(100)
);

--create dim dish name

CREATE TABLE DIM_DISH (
	DISH_ID INT GENERATED ALWAYS AS IDENTITY (
		START
		WITH
			1 INCREMENT BY 1
	) PRIMARY KEY,
	DISH_NAME VARCHAR(200)
);
----------------------
--create a fact table
----------------------
DROP TABLE IF EXISTS FACT_TABLE;
CREATE TABLE FACT_TABLE (
	ORDER_ID INT GENERATED ALWAYS AS IDENTITY (
		START
		WITH
			1 INCREMENT BY 1
	) PRIMARY KEY,
	DATE_ID INT,
	PRICE_INR DECIMAL(10, 2),
	RATING DECIMAL(10, 2),
	RATING_COUNT INT,
	LOCATION_ID INT,
	RESTAURANT_ID INT,
	CATEGORY_ID INT,
	DISH_ID INT,
	FOREIGN KEY (DATE_ID) REFERENCES DIM_DATE (DATE_ID),
	FOREIGN KEY (LOCATION_ID) REFERENCES DIM_LOCATION (LOCATION_ID),
	FOREIGN KEY (RESTAURANT_ID) REFERENCES DIM_RESTAURANT (RESTAURANT_ID),
	FOREIGN KEY (CATEGORY_ID) REFERENCES DIM_CATEGORY (CATEGORY_ID),
	FOREIGN KEY (DISH_ID) REFERENCES DIM_DISH (DISH_ID)
);
SELECT * FROM DIM_DATE;
-----------------------------------------------------------------
-------------INSERTING DATA TO EACH DIM_TABLES-------------------
-----------------------------------------------------------------
INSERT INTO
	DIM_DATE (
		FULL_DATE,
		YEARS,
		MONTHS,
		MONTH_NAME,
		QUARTER,
		DAYS,
		WEEK
	)
SELECT DISTINCT
	ORDER_DATE,
	EXTRACT(
		YEAR
		FROM
			ORDER_DATE
	),
	EXTRACT(
		MONTH
		FROM
			ORDER_DATE
	),
	TO_CHAR(ORDER_DATE, 'FMMonth'),
	EXTRACT(
		QUARTER
		FROM
			ORDER_DATE
	),
	EXTRACT(
		DAY
		FROM
			ORDER_DATE
	),
	EXTRACT(
		WEEK
		FROM
			ORDER_DATE
	)
FROM
	SWIGGY_ANALYSIS;

SELECT
	*
FROM
	DIM_DATE;

--INSERT DATA INSIDE DIM_LOCATION

INSERT INTO
	DIM_LOCATION (STATES, CITY, LOCATIONS)
SELECT DISTINCT
	STATES,
	CITY,
	LOCATIONS
FROM
	SWIGGY_ANALYSIS;

SELECT
	*
FROM
	DIM_LOCATION;

--INSERT DATA INTO DIM_RESTAURANT

INSERT INTO
	DIM_RESTAURANT (RESTAURANT_NAME)
SELECT DISTINCT
	RESTAURANT_NAME
FROM
	SWIGGY_ANALYSIS;

SELECT
	*
FROM
	DIM_RESTAURANT;

-- INSERT DATA INTO DIM_CATEGORY

INSERT INTO
	DIM_CATEGORY (CATEGORY)
SELECT DISTINCT
	CATEGORY
FROM
	SWIGGY_ANALYSIS;

SELECT
	*
FROM
	DIM_CATEGORY;

-- INSERT DATA INTO DIM_DISH

INSERT INTO
	DIM_DISH (DISH_NAME)
SELECT DISTINCT
	NAME_OF_THE_DISH
FROM
	SWIGGY_ANALYSIS;

SELECT
	*
FROM
	DIM_DISH;

SELECT
	*
FROM
	SWIGGY_ANALYSIS;
--------------------------
--POPULATE THE FACT TABLE
--------------------------

INSERT INTO
	FACT_TABLE (
		DATE_ID,
		PRICE_INR,
		RATING,
		RATING_COUNT,
		LOCATION_ID,
		RESTAURANT_ID,
		CATEGORY_ID,
		DISH_ID
	)
SELECT 
	DD.DATE_ID,
	S.PRICE,
	S.RATING,
	S.RATING_COUNT,
	LC.LOCATION_ID,
	R.RESTAURANT_ID,
	CT.CATEGORY_ID,
	D.DISH_ID
FROM
	SWIGGY_ANALYSIS S
	JOIN DIM_DATE DD ON DD.FULL_DATE = S.ORDER_DATE
	JOIN DIM_LOCATION LC ON LC.STATES = S.STATES
	AND LC.CITY = S.CITY
	AND LC.LOCATIONS = S.LOCATIONS
	JOIN DIM_RESTAURANT R ON R.RESTAURANT_NAME = S.RESTAURANT_NAME
	JOIN DIM_CATEGORY CT ON CT.CATEGORY = S.CATEGORY
	JOIN DIM_DISH D ON D.DISH_NAME = S.NAME_OF_THE_DISH;

--CREATE THE SCHEMA
SELECT
	*
FROM
	FACT_TABLE F
	JOIN DIM_DATE D ON F.DATE_ID = D.DATE_ID
	JOIN DIM_LOCATION L ON F.LOCATION_ID = L.LOCATION_ID
	JOIN DIM_RESTAURANT R ON F.RESTAURANT_ID = R.RESTAURANT_ID
	JOIN DIM_CATEGORY CT ON F.CATEGORY_ID = CT.CATEGORY_ID
	JOIN DIM_DISH DS ON F.DISH_ID = DS.DISH_ID;

---------------------------------------------------------------------
----------------------------PERFORMING KPI's-------------------------
---------------------------------------------------------------------
--TOTAL ORDERS
SELECT
	COUNT(*) AS TOTAL_ORDERS
FROM
	FACT_TABLE;
--NOTE:- 197403 ORDERS MADE
-----------------------------------

-- TOTAL REVENUE(IN_INR_MILLION)
SELECT
	'₹' || TO_CHAR(
		ROUND(SUM(PRICE_INR) / 1000000.00, 2),
		'FM9999.00'
	) || 'INR_MILLION' AS TOTAL_REVENUE
FROM
	FACT_TABLE;
--NOTE:- TOTAL REVENUE OF ₹53.00INR_MILLION
--------------------------------------------

--AVERAGE DISH PRICE
SELECT
	'₹' || TO_CHAR(ROUND(AVG(PRICE_INR), 2), 'FM999.00') AS AVERAGE_DISH_PRICE
FROM
	FACT_TABLE;
--NOTE:- AVERAGE PRICE PER DISH IS ₹268.50
------------------------------------------

--AVERAGE RATING
SELECT
	ROUND(AVG(RATING), 2) AS AVG_RATING
FROM
	FACT_TABLE;
--NOTE:- AVERAGE RATING IS 4.34
-------------------------------


------------------------------------------------
----------DATE BASED ANALYSIS-------------------
------------------------------------------------
--MONTHLY ORDER TRENDS
SELECT
	DM.YEARS,
	DM.MONTHS,
	DM.MONTH_NAME,
	COUNT(*) AS TOTAL_ORDERS
FROM
	FACT_TABLE F
	JOIN DIM_DATE DM ON F.DATE_ID = DM.DATE_ID
GROUP BY
	DM.YEARS,
	DM.MONTHS,
	DM.MONTH_NAME;

--NOTE:- ORDERS PEAKED AT THE BEGINING OF THE YEAR IN JANUARY
-------------------------------------------------------------

--QUARTERLY ORDER TRENDS
SELECT
	DM.YEARS,
	DM.QUARTER,
	COUNT(*) AS QURARTERLY_ORDER_SUMMARY
FROM
	FACT_TABLE F
	JOIN DIM_DATE DM ON F.DATE_ID = DM.DATE_ID
GROUP BY
	DM.YEARS,
	DM.QUARTER;
--NOTE:- THE HIGHEST ORDERS WERE PLACED DURING THE SECOND QUARTER OF THE FINANCIAL YEAR 2025
---------------------------------------------------------------------------------------------

--DAY OF WEEK PATTERN(MON TO SUN);
SELECT
	TO_CHAR(DM.FULL_DATE, 'DY') AS DAILY_SUMMARY,
	COUNT(*) AS TOTAL_ORDERS
FROM
	FACT_TABLE F
	JOIN DIM_DATE DM ON F.DATE_ID = DM.DATE_ID
GROUP BY
	DAILY_SUMMARY
ORDER BY
	TOTAL_ORDERS DESC;
--NOTE:- SAT HAD THE HIGHEST ORDER FREQUENCY IN THE ENTIRE YEAR
---------------------------------------------------------------


---------------------------------------------------------------
--------------LOCATION BASED ANALYSIS--------------------------
---------------------------------------------------------------
--TOP 10 CITIES BY REVENUE_VOLUME
SELECT
	LC.CITY,
	SUM(F.PRICE_INR) REVENUE_VOLUME
FROM
	FACT_TABLE F
	JOIN DIM_LOCATION LC ON F.LOCATION_ID = LC.LOCATION_ID
GROUP BY
	LC.CITY
ORDER BY
	REVENUE_VOLUME DESC
LIMIT
	10;
--NOTE:- AMONG THE TOP 10 CITITES BENGALURU TOPPED THE TABLE FOLLOWED BY LUCKNOW AND HYDERBAD
----------------------------------------------------------------------------------------------


--REVENUE CONTRIBUTION BY STATE
SELECT
	LC.STATES,
	SUM(F.PRICE_INR) AS REVENUE_CONTRIBUTION
FROM
	FACT_TABLE F
	JOIN DIM_LOCATION LC ON F.LOCATION_ID = LC.LOCATION_ID
GROUP BY
	LC.STATES
ORDER BY
	REVENUE_CONTRIBUTION DESC;

--NOTE:- THE STATE OF KARNATAKA WAS THE HIGHERST 
----------------------------------------------------
--REVENUE CONTRIBUTOR FOLLOWED BY UTTAR PRADESH AND TELANGANA
-------------------------------------------------------------


--------------------------------------------------
-------------FOOD PERFORMANCES--------------------
--------------------------------------------------
--TOP 10 CATEGORY FOODS
SELECT
	C.CATEGORY,
	COUNT(*) AS TOTAL_ORDERS
FROM
	FACT_TABLE F
	JOIN DIM_CATEGORY C ON F.CATEGORY_ID = C.CATEGORY_ID
GROUP BY
	C.CATEGORY
ORDER BY
	TOTAL_ORDERS DESC
LIMIT
	10;
--NOTE:- RECOMMENDED FOOD TOPS THE TABLE FOLLOWED BY MAIN COURSE AND DESERT
-----------------------------------------------------------------------------


--TOP 10 RESTAURANTS BY ORDER
SELECT
	DR.RESTURANT_NAME,
	SUM(F.PRICE_INR) AS TOTAL_REVENUE
FROM
	FACT_TABLE F
	JOIN DIM_RESTAURANT DR ON F.RESTAURANT_ID = DR.RESTAURANT_ID
GROUP BY
	DR.RESTURANT_NAME
ORDER BY
	TOTAL_REVENUE DESC
LIMIT
	10;
--NOTE:- KFC HAS THE HIGHEST REVENUE CONTRIBUTION FOLLOWED BY McDonald's AND PIZZA HUT.
---------------------------------------------------------------------------------------

--CITIES WITH THE TOP PERFORMING RESTAURANT BY REVENUE
SELECT
	*
FROM
	(
		SELECT
			L.CITY,
			R.RESTURANT_NAME,
			SUM(F.PRICE_INR) AS REVENUE,
			RANK() OVER (
				PARTITION BY
					L.CITY
				ORDER BY
					SUM(F.PRICE_INR) DESC
			) AS RNK
		FROM
			FACT_TABLE F
			JOIN DIM_LOCATION L ON F.LOCATION_ID = L.LOCATION_ID
			JOIN DIM_RESTAURANT R ON F.RESTAURANT_ID = R.RESTAURANT_ID
		GROUP BY
			L.CITY,
			R.RESTURANT_NAME
	) T
WHERE
	RNK = 1;
--NOTE :- AGARTALA IS THE TOP PERFORMING CITY BY REVENUE AND DONMIO'S PIZZA IS THE TOP RESTAURANT HERE
------------------------------------------------------------------------------------------------------

--MOST ORDERED DISHES
SELECT
	DM.DISH_NAME,
	COUNT(F.DISH_ID) AS DISH_ORDERED
FROM
	FACT_TABLE F
	JOIN DIM_DISH DM ON F.DISH_ID = DM.DISH_ID
GROUP BY
	DM.DISH_NAME
ORDER BY
	DISH_ORDERED DESC;

--NOTE:- CHOCO LAVA CAKE ISTHE MOST ORDERED DISH FOLLOWED BY VEG FRIED RICE AND CHICKEN SAUSAGE
------------------------------------------------------------------------------------------------


--CUSINE PERFORMANCE
SELECT
	C.CATEGORY,
	COUNT(*) AS CUSINES,
	ROUND(AVG(F.RATING), 2) AS AVG_RATING
FROM
	FACT_TABLE F
	JOIN DIM_CATEGORY C ON F.CATEGORY_ID = C.CATEGORY_ID
GROUP BY
	C.CATEGORY
ORDER BY
	CUSINES DESC;
--NOTE:- THE MOST ORDERD DISHES ARE DISHES THAT ARE RECOMMENDED FOLLOWED BY MAIN COURSE AND DESERTS.
----------------------------------------------------------------------------------------------------


-------------------------------------------------------
----------ORDER DISTRIBUTION PER PRICE RANGE-----------
-------------------------------------------------------
SELECT
	CASE
		WHEN PRICE_INR < 100 THEN 'UNDER 100'
		WHEN PRICE_INR BETWEEN 100 AND 199  THEN '100-199'
		WHEN PRICE_INR BETWEEN 200 AND 299  THEN '200-299'
		WHEN PRICE_INR BETWEEN 300 AND 399  THEN '300-399'
		WHEN PRICE_INR BETWEEN 400 AND 499  THEN '400-499'
		ELSE '500+'
	END AS PRICE_RANGE,
	COUNT(*) AS TOTAL_PRODUCT
FROM
	FACT_TABLE
GROUP BY
	CASE
		WHEN PRICE_INR < 100 THEN 'UNDER 100'
		WHEN PRICE_INR BETWEEN 100 AND 199  THEN '100-199'
		WHEN PRICE_INR BETWEEN 200 AND 299  THEN '200-299'
		WHEN PRICE_INR BETWEEN 300 AND 399  THEN '300-399'
		WHEN PRICE_INR BETWEEN 400 AND 499  THEN '400-499'
		ELSE '500+'
	END
ORDER BY
	TOTAL_PRODUCT DESC;
--NOTE:- MAXIMUM ORDERS WERE MADE OF PRODUCTS UNDER THE PRICE RANGE OF 100-199 FOLLOWED BY 200-299 	
---------------------------------------------------------------------------------------------------	
	
